#ifndef _65C02S_MNEMONICS_H
#define _65C02S_MNEMONICS_H

const char *mnemonic[0xFF + 1] = {
	 "BRK",  // 00
	 "ORA",  // 01
	 "",     // 02
	 "",     // 03
	 "TSB",  // 04
	 "ORA",  // 05
	 "ASL",  // 06
	 "RMV0", // 07
	 "PHP",  // 08
	 "ORA",  // 09
	 "ASL",  // 0a
	 "",     // 0b
	 "TSP",  // 0c
	 "ORA",  // 0d
	 "ASL",  // 0e
	 "BBR0", // 0f
	 "BPL",  // 10
	 "ORA",  // 11
	 "ORA",  // 12
	 "",     // 13
	 "TRB",  // 14
	 "ORA",  // 15
	 "ASL",  // 16
	 "RMB1", // 17
	 "CLC",  // 18
	 "ORA",  // 19
	 "INC",  // 1a
	 "",     // 1b
	 "TRB",  // 1c
	 "ORA",  // 1d
	 "ASL",  // 1e
	 "BBR1", // 1f
	 "JSR",  // 20
	 "AND",  // 21
	 "",     // 22
	 "",     // 23
	 "BIT",  // 24
	 "AND",  // 25
	 "ROL",  // 26
	 "RMB2", // 27
	 "PLP",  // 28
	 "AND",  // 29
	 "ROL",  // 2a
	 "",     // 2b
	 "BIT",  // 2c
	 "AND",  // 2d
	 "ROL",  // 2e
	 "BBR2", // 2f
	 "BMI",  // 30
	 "AND",  // 31
	 "AND",  // 32
	 "",     // 33
	 "BIT",  // 34
	 "AND",  // 35
	 "ROL",  // 36
	 "RMB3", // 37
	 "SEC",  // 38
	 "AND",  // 39
	 "DEC",  // 3a
	 "",     // 3b
	 "BIT",  // 3c
	 "AND",  // 3d
	 "ROL",  // 3e
	 "BBR3", // 3f
	 "RTI",  // 40
	 "EOR",  // 41
	 "",     // 42
	 "",     // 43
	 "",     // 44
	 "EOR",  // 45
	 "LSR",  // 46
	 "RMB4", // 47
	 "PHA",  // 48
	 "EOR",  // 49
	 "LSR",  // 4a
	 "",     // 4b
	 "JMP",  // 4c
	 "EOR",  // 4d
	 "LST",  // 4e
	 "BBR4", // 4f
	 "BVC",  // 50
	 "EOR",  // 51
	 "EOR",  // 52
	 "",     // 53
	 "",     // 54
	 "EOR",  // 55
	 "LSR",  // 56
	 "RMB5", // 57
	 "CLI",  // 58
	 "EOR",  // 59
	 "PHY",  // 5a
	 "",     // 5b
	 "",     // 5c
	 "EOR",  // 5d
	 "LSR",  // 5e
	 "BBR5", // 5f
	 "RTS",  // 60
	 "ADC",  // 61
	 "",     // 62
	 "",     // 63
	 "STZ",  // 64
	 "ADC",  // 65
	 "ROR",  // 66
	 "RMB6", // 67
	 "PLA",  // 68
	 "ADC",  // 69
	 "ROR",  // 6a
	 "",     // 6b
	 "JMP",  // 6c
	 "ADC",  // 6d
	 "ROR",  // 6e
	 "BBR6", // 6f
	 "BVS",  // 70
	 "ADC",  // 71
	 "ADC",  // 72
	 "",     // 73
	 "STZ",  // 74
	 "ADC",  // 75
	 "ROR",  // 76
	 "RMB7", // 77
	 "SEI",  // 78
	 "ADC",  // 79
	 "PLY",  // 7a
	 "",     // 7b
	 "JMP",  // 7c
	 "ADC",  // 7d
	 "ROR",  // 7e
	 "BBR7", // 7f
	 "BRA",  // 80
	 "STA",  // 81
	 "",     // 82
	 "",     // 83
	 "STY",  // 84
	 "STA",  // 85
	 "STZ",  // 86
	 "SMB0", // 87
	 "DEY",  // 88
	 "BIT",  // 89
	 "TXA",  // 8a
	 "",     // 8b
	 "STY",  // 8c
	 "STA",  // 8d
	 "STX",  // 8e
	 "BBS0", // 8f
	 "BCC",  // 90
	 "STA",  // 91
	 "STA",  // 92
	 "",     // 93
	 "STY",  // 94
	 "STA",  // 95
	 "STZ",  // 96
	 "SMB1", // 97
	 "TYA",  // 98
	 "STA",  // 99
	 "TSX",  // 9a
	 "",     // 9b
	 "STZ",  // 9c
	 "STA",  // 9d
	 "STZ",  // 9e
	 "BBS1", // 9f
	 "LDY",  // a0
	 "LDA",  // a1
	 "LDX",  // a2
	 "",     // a3
	 "LDY",  // a4
	 "LDA",  // a5
	 "LDX",  // a6
	 "SMB2", // a7
	 "TAY",  // a8
	 "LDA",  // a9
	 "TAX",  // aa
	 "",     // ab
	 "LDY",  // ac
	 "LDA",  // ad
	 "LDX",  // ae
	 "BBS2", // af
	 "BCS",  // b0
	 "LDA",  // b1
	 "LDA",  // b2
	 "",     // b3
	 "LDY",  // b4
	 "LDA",  // b5
	 "LDX",  // b6
	 "SMB3", // b7
	 "CLV",  // b8
	 "LDA",  // b9
	 "TSX",  // ba
	 "",     // bb
	 "LDY",  // bc
	 "LDA",  // bd
	 "LDX",  // be
	 "BBS3", // bf
	 "CPY",  // c0
	 "CMP",  // c1
	 "",     // c2
	 "",     // c3
	 "CPY",  // c4
	 "CMP",  // c5
	 "DEC",  // c6
	 "SMB4", // c7
	 "INY",  // c8
	 "CMP",  // c9
	 "DEX",  // ca
	 "WAI",  // cb
	 "CPY",  // cc
	 "CMP",  // cd
	 "DEC",  // ce
	 "BBS4", // cf
	 "BNE",  // d0
	 "CMP",  // d1
	 "CMP",  // d2
	 "",     // d3
	 "",     // d4
	 "CMP",  // d5
	 "DEC",  // d6
	 "SMB5", // d7
	 "CLD",  // d8
	 "CMP",  // d9
	 "PHX",  // da
	 "STP",  // db
	 "",     // dc
	 "CMP",  // dd
	 "DEC",  // de
	 "BBS5", // df
	 "CPX",  // e0
	 "SBC",  // e1
	 "",     // e2
	 "",     // e3
	 "CPX",  // e4
	 "SBC",  // e5
	 "INC",  // e6
	 "SMB6", // e7
	 "INX",  // e8
	 "SBC",  // e9
	 "NOP",  // ea
	 "",     // eb
	 "CPX",  // ec
	 "SBC",  // ed
	 "INC",  // ee
	 "BBS6", // ef
	 "BEQ",  // f0
	 "SBC",  // f1
	 "SBC",  // f2
	 "",     // f3
	 "",     // f4
	 "SBC",  // f5
	 "INC",  // f6
	 "SMB7", // f7
	 "SED",  // f8
	 "SBC",  // f9
	 "PLX",  // fa
	 "",     // fb
	 "",     // fc
	 "SBC",  // fd
	 "INC",  // fe
	 "BBS7"  // ff
};

#endif
